### ISSUE TITLE
where can I find the file "~/Desktop/Aim1/Main-data/Demographic-data/nst-est2019-alldata.csv" thanks.

### ISSUE THREAD

**Issue by liamxg** [ldamodaran/US-H3N2-Diffusion-2011-2020#1]

**Comment by liamxg** [comment]
@ldamodaran could you please upload the data files, thanks.

**Comment by ldamodaran** [comment]
Hi we are currently preparing the materials for publication. all data for the project will be made prior to publication and i can notify you when this happens. For the census data you can find that at the U.S. Census Divisions website, it is a publically available dataset, let me know if you have issues finding it on the website.

**Comment by liamxg** [comment]
hi @ldamodaran , very glad to hear from you. I am very interested about your project.

**Comment by liamxg** [comment]
many files that I can not find in the GLM fold, for example: climate_data <- read.csv("~/Desktop/Aim1/Main-data/climate-data/nclimdiv-averages-flu-sep-april.csv", header = TRUE)
stateabv <- read.csv("~/Desktop/Aim1/Main-data/climate-data/US-states-postabv.csv", header = TRUE)

**Comment by liamxg** [comment]
and this file 2011-2020-jointrates.tsv.

**Comment by liamxg** [comment]
@ldamodaran

**Comment by ldamodaran** [comment]
HI thank you for your interest, we are finishing the project and all relevant data files will be added in the next month or so. Please check back in the future.

**Comment by liamxg** [comment]
@ldamodaran thanks. that's great, can not wait for this.

**Comment by liamxg** [comment]
@ldamodaran any update for this?
